### ISSUE TITLE
Hard to mock with

### ISSUE THREAD

**Issue by jestingrabbit** [roryqueue/redets#1]
I'm trying to use this as a test mock for `redix`, which defines `Redix.command/2-3`. You have `FakeRedis.command/2`. This mismatch leads to a little bit of cruft. It would be nice have the same calling patterns enabled.

Thanks for at least defining `command` though. We push everything we do with redis through that, and having it in the mock is a big plus.

**Comment by roryqueue** [comment]
@jestingrabbit sorry, just saw this issue-- thanks for letting me know, will update soon to match!
